apiVersion: pi-app-deployer/v1
kind: Manifest
name: pi-sensor-agent
executable: pi-sensor-agent
heroku:
  app: pi-sensor
  env:
    - CLOUDMQTT_URL
    - CLOUDMQTT_AGENT_USER
    - CLOUDMQTT_AGENT_PASSWORD
env: # non-secret env vars, required to be passed in agent install
  - SENSOR_SOURCE # varies by deployment
---
apiVersion: pi-app-deployer/v1
kind: Manifest
name: door-light
executable: door-light
heroku:
  app: pi-sensor
  env:
    - CLOUDMQTT_URL
    - DOOR_LIGHT_DOOR
    - DOOR_LIGHT_DEVICE_NAMES
    - CLOUDMQTT_APP_USER
    - CLOUDMQTT_APP_PASSWORD
---
apiVersion: pi-app-deployer/v1
kind: Manifest
name: pi-sensor-agent-staging
executable: pi-sensor-agent
heroku:
  app: pi-sensor-staging
  env:
    - CLOUDMQTT_URL
env: # non-secret env vars, required to be passed in agent install
  - SENSOR_SOURCE # varies by deployment
