- name: Deploy Agents
  hosts: all
  remote_user: pi
  become: true
  vars:
    OP_CONNECT_TOKEN: "{{ lookup('ansible.builtin.env', 'OP_CONNECT_TOKEN') }}"
    OP_CONNECT_HOST: "{{ lookup('ansible.builtin.env', 'OP_CONNECT_HOST') }}"
  tasks:
  - name: Make directory
    file:
      path: /usr/local/src/pi-sensor-agent/
      state: directory
  - name: Copy log-forwader binary
    ansible.builtin.copy:
      src: ./build/agent-log-forwarder
      dest: /usr/local/src/pi-sensor-agent/agent-log-forwarder
      mode: '0755'
      owner: root
      group: root
      force: yes
  - name: Write 1password env file
    ansible.builtin.template:
      src: ./agent/deployment/op-env.j2
      dest: /usr/local/src/pi-sensor-agent/.op-env
      owner: root
      group: root
    no_log: True
  - name: Write op cli env-file template
    ansible.builtin.copy:
      src: ./agent/deployment/env-file.tmpl
      dest: /usr/local/src/pi-sensor-agent/.env-file.tmpl
      owner: root
      group: root
      force: yes
  - name: Copy agent systemd unit file
    ansible.builtin.template:
      src: ./agent/deployment/systemd-unit.service.j2
      dest: /etc/systemd/system/pi-sensor-agent-v2.service
      owner: root
      group: root
    no_log: True
  - name: Copy agent binary
    ansible.builtin.copy:
      src: ./build/pi-sensor-agent
      dest: /usr/local/src/pi-sensor-agent/pi-sensor-agent
      mode: '0755'
      owner: pi
      group: pi
      force: yes
  - name: Restart systemd unit
    become: true
    systemd:
      daemon_reload: yes
      enable: yes
      force: yes
      name: pi-sensor-agent-v2
      state: restarted
