version: '3.8'
services:
  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass abc
    volumes: 
      - cache:/data
  db:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto:1.6.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '1883:1883'
      - '9001:9001'

volumes:
  cache:
    driver: local
  db:
    driver: local
