- name: Deploy server
  hosts: all
  remote_user: mqtt-server
  become: true
  # todo: fail when these env vars are unset
  vars:
    MOSQUITTO_USER: "{{ lookup('ansible.builtin.env', 'MOSQUITTO_USER') }}"
    MOSQUITTO_PASS: "{{ lookup('ansible.builtin.env', 'MOSQUITTO_PASS') }}"
  tasks:
  - name: Ensure passwd file exists
    copy:
      content: ""
      dest: /etc/mosquitto/passwd
      force: false
      group: sys
      owner: root
      mode: 0664
  - name: Configure mosquitto_passwd
    shell:
      cmd: sudo mosquitto_passwd -b /etc/mosquitto/passwd {{ MOSQUITTO_USER }} {{ MOSQUITTO_PASS }}
  - name: Copy mosquitto.conf
    ansible.builtin.copy:
      src: ./mosquitto.conf
      dest: /etc/mosquitto/conf.d/mosquitto.conf
      mode: 0664
      owner: root
      group: root
      force: yes
  - name: Restart mosquitto systemd unit
    become: true
    systemd:
      daemon_reload: yes
      enabled: yes
      force: yes
      name: mosquitto
      state: restarted
