name: Build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            build/pi-sensor-agent
            build/agent-log-forwarder
      # todo: set SHORT_SHA in pr or main workflow
      - name: Build and push docker image
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo ${GH_TOKEN} | docker login ghcr.io -u 'andrewmarklloyd' --password-stdin
          image="ghcr.io/andrewmarklloyd/pi-sensor:${SHORT_SHA}"
          docker build -t ${image} .
          docker push ${image}
