name: Build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            build/pi-sensor-server
            build/op-limit-check-entry
            frontend/build
