name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Deploy Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_SHA:  ${{ github.sha }}
          SERVER_API_KEY: ${{ secrets.SERVER_API_KEY_PROD }}
        run: ./.github/scripts/deploy-heroku.sh pi-sensor
      - name: Deploy Pi Sensor Agent
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-sensor
          manifestName: pi-sensor-agent
          host: https://pi-app-deployer.herokuapp.com
      - name: Deploy Door Light
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-sensor
          manifestName: door-light
          host: https://pi-app-deployer.herokuapp.com
