name: Main Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: make build-ci
      - uses: actions/upload-artifact@v2
        with:
          name: app_${{ github.sha }}
          path: |
            door-light
            pi-sensor-agent
            .pi-app-deployer.yaml
