name: Main Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Deploy container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          which docker
          docker ps
          # docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
          # heroku container:login
          # heroku container:push web -a pi-sensor-staging
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '1.16.0'
      # - name: Install dependencies
      #   run: |
      #     go get -u golang.org/x/lint/golint
      # - name: Check
      #   run: |
      #     make vet
      #     make test
      # - name: Run build
      #   run: make build-ci
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: app_${{ github.sha }}
      #     path: |
      #       door-light
      #       pi-sensor-agent
      #       .pi-app-deployer.yaml
      # - name: Build front end
      #   run: |
      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      #     . $HOME/.nvm/nvm.sh
      #     cd server/frontend
      #     nvm install
      #     nvm use
      #     npm install
      #     npm run build

