name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      # - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: pi-sensor
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
      #     usedocker: true
      #     healthcheck: "https://pi-sensor.herokuapp.com/health"
      #     checkstring: "ok"
      - name: Deploy Pi Sensor Agent
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-sensor
          manifestName: pi-sensor-agent
          host: https://pi-app-deployer.herokuapp.com
      - name: Deploy Door Light
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-sensor
          manifestName: door-light
          host: https://pi-app-deployer.herokuapp.com
