name: Main Build Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - uses: actions/upload-artifact@v2
        with:
          name: app_${{ github.sha }}
          path: |
            door-light
            pi-sensor-agent
            .pi-app-deployer.yaml
      - name: Infrastructure Config Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          HEROKU_APP=pi-sensor-staging ./.github/scripts/infra-config.sh
      - name: Deploy Heroku Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_SHA:  ${{ github.sha }}
        run: ./.github/scripts/deploy-heroku.sh pi-sensor-staging
      - name: Infrastructure Config Production
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          HEROKU_APP=pi-sensor ./.github/scripts/infra-config.sh
      - name: Deploy Heroku Production
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_SHA:  ${{ github.sha }}
        run: ./.github/scripts/deploy-heroku.sh pi-sensor
      - name: Deploy DO
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
          OPCONNECT_CERT: ${{ secrets.OPCONNECT_CERT }}
        run: ./.github/scripts/deploy-do.sh
      - name: Start tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Deploy agents
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-agent.yaml
          directory: ./agent/deployment/
          key: ${{ secrets.AGENT_SSH_KEY }}
          inventory: |
            [all]
            ${{ secrets.AGENT_HOSTS }}
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
