name: Main Build Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - name: Deploy DO
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
          OPCONNECT_CERT: ${{ secrets.OPCONNECT_CERT }}
        run: ./.github/scripts/deploy-do.sh
      - name: Start tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Deploy agents
        uses: dawidd6/action-ansible-playbook@v2
        env:
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
        with:
          playbook: deploy-agent.yaml
          key: ${{ secrets.AGENT_SSH_KEY }}
          options: |
            --inventory inventory.yaml
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
