name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  pi_app_deployer:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - name: Deploy Application
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-sensor
          manifestName: door-light
          host: https://pi-app-deployer.herokuapp.com
