name: Pi-App-Deployer
on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Service action to perform on the pi app: START, STOP, or RESTART'
        required: true
        default: 'RESTART'
jobs:
  runAction:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Service Action
      env:
        ACTION: ${{ github.event.inputs.action }}
      run: ./.github/scripts/service-action.sh
