name: Main Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - name: Add OP connect cert
        run: |
          echo "${OPCONNECT_CERT}" > opconnect.crt
          sudo mv ./opconnect.crt /usr/local/share/ca-certificates/opconnect.crt
          sudo update-ca-certificates
        env:
          OPCONNECT_CERT: ${{ secrets.OPCONNECT_CERT }}
      - name: Update firewall
        run: |
          go install github.com/andrewmarklloyd/do-app-firewall-entrypoint@latest
          do-app-firewall-entrypoint
        env:
          STATIC_INBOUND_IP: ${{ secrets.STATIC_INBOUND_IP }}
          FIREWALL_NAME: ${{ secrets.FIREWALL_NAME }}
          FIREWALL_PORT: ${{ secrets.FIREWALL_PORT }}
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.1.0
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SECRET: op://github-ci/config/hello
      # - name: Print masked secret
      #   run: echo "Secret: ${{ steps.op-load-secret.outputs.SECRET }}"
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
