name: Pull Request
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
