name: Main Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint
      - name: Check
        run: |
          make vet
          make test
      # - name: Cache Build
      #   uses: actions/cache@v1
      #   with:
      #     path: |
      #       ./pi-sensor-server
      #       ./server/frontend/build
      #     key: ${{ runner.OS }}-build
      - name: Run build
        run: |
          make build
          make build-frontend
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Deploy Heroku Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_SHA:  ${{ github.sha }}
        run: ./.github/scripts/deploy-heroku.sh pi-sensor-staging
