name: Main Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - name: Update firewall
        run: |
          go install github.com/andrewmarklloyd/do-app-firewall-entrypoint@latest
          /go/bin/do-app-firewall-entrypoint
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SECRET: op://github-ci/config/hello
      # - name: Print masked secret
      #   run: echo "Secret: ${{ steps.op-load-secret.outputs.SECRET }}"
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
