name: Main Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Check
        run: |
          make vet
          make test
      - name: Run build
        run: |
          make build-ci
      - name: Infrastructure Config
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          HEROKU_APP=pi-sensor-staging ./.github/scripts/infra-config.sh
      - name: Deploy Heroku Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_SHA:  ${{ github.sha }}
          SERVER_API_KEY: ${{ secrets.SERVER_API_KEY_STAGING }}
        run: ./.github/scripts/deploy-heroku.sh pi-sensor-staging
