name: Main Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
# temp disable for faster test deploys
      # - name: Check
      #   run: |
      #     make vet
      #     make test
      - name: Run build
        run: |
          make build-ci
      - name: Deploy DO
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: ./.github/scripts/deploy-do.sh pi-sensor-staging
